const cfg=window.INVITATION_CONFIG;const $=s=>document.querySelector(s);const form=$('#rsvpForm'),status=$('#formStatus'),persons=$('#persons'),guestNames=$('#guestNames');
const i18n={en:{tapOpen:'Tap to open our invitation',details:'Details',location:'Location',title:'THE CELEBRATION CONTINUES',tagline:'Same love · Different kind of fun',date:'Saturday, 10 October 2026',youreInvited:"You're Invited ♡",afterWedding:'After the wedding…',moreCelebration:'A Little More About Our Celebration',story:"We said ‘I do’… now let’s continue the celebration. Join us for a cozy night filled with great food, amazing company, and unforgettable memories at Padrino.",food:'Delicious Food',company:'Amazing Company',vibes:'Great Vibes',love:'Because love deserves an afterparty',venueLabel:'The Venue',sheraton:'Padrino · Sheraton Al Matar, Cairo',charge:'Minimum charge: 500 EGP per person',maps:'Open in Google Maps →',rsvpBy:'Kindly let us know by Thursday, 1 October 2026',celebrating:'Will you be celebrating with us?',yes:"Yes, I'll be there",no:"Unfortunately, I can't attend",yourName:'Your name',phone:'Phone number',persons:'Number of persons',note:'Leave a happy note for Mark & Marina 💜',submit:'Submit RSVP ♡',cantWait:"We can't wait to celebrate with you",guest:'Guest',closed:'RSVPs are now closed. We can’t wait to celebrate with you! 💜',success:'We can’t wait to celebrate with you! 💜',declined:'Thank you for letting us know. 💜',waiting:'Your RSVP has been added to the waiting list. We’ll let you know if space becomes available. 💜',configure:'The website is ready, but the Google Sheet endpoint still needs to be connected.'},ar:{tapOpen:'اضغط لفتح الدعوة',details:'التفاصيل',location:'المكان',title:'الاحتفال لسه مكمل',tagline:'نفس الحب · واحتفال بطعم مختلف',date:'السبت ١٠ أكتوبر ٢٠٢٦',youreInvited:'مستنيينكم معانا ♡',afterWedding:'بعد الفرح…',moreCelebration:'لسه عندنا احتفال تاني',story:'قلنا «نعم»… ودلوقتي نكمل الاحتفال سوا. مستنيينكم في ليلة لطيفة فيها أكل حلو وصحبة أحلى وذكريات مميزة في Padrino.',food:'أكل لذيذ',company:'أحلى صحبة',vibes:'أجواء حلوة',love:'لأن الحب يستاهل After Party',venueLabel:'المكان',sheraton:'Padrino · شيراتون المطار، القاهرة',charge:'Minimum charge: 500 جنيه للفرد',maps:'افتح المكان على Google Maps ←',rsvpBy:'من فضلك أكد حضورك قبل الخميس ١ أكتوبر ٢٠٢٦',celebrating:'هتحتفل معانا؟',yes:'أيوه، هكون معاكم',no:'للأسف مش هقدر أحضر',yourName:'اسمك',phone:'رقم الموبايل',persons:'عدد الأشخاص',note:'سيبلنا رسالة حلوة لمارك ومارينا 💜',submit:'تأكيد الحضور ♡',cantWait:'مستنيين نحتفل معاكم',guest:'اسم الشخص',closed:'تم إغلاق تأكيد الحضور. مستنيين نحتفل معاكم! 💜',success:'مستنيين نحتفل معاكم! 💜',declined:'شكراً إنك عرّفتنا. 💜',waiting:'تم إضافة حجزك لقائمة الانتظار، وهنبلغك لو مكان أصبح متاح. 💜',configure:'الموقع جاهز، لكن لسه محتاجين نوصل رابط Google Sheet.'}};
let lang='en';function t(k){return i18n[lang][k]||k}function translate(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));renderGuests()}
$('#langToggle').onclick=()=>{lang=lang==='en'?'ar':'en';translate()};
$('#openInvitation').onclick=()=>{$('#opening').classList.add('opened');const a=$('#music');if(a.querySelector('source'))a.play().catch(()=>{})};
$('#musicToggle').onclick=()=>{const a=$('#music');if(!a.querySelector('source'))return;if(a.paused)a.play();else a.pause()};
function renderGuests(){guestNames.innerHTML='';const n=Number(persons.value);for(let i=1;i<=n;i++){const l=document.createElement('label');l.innerHTML=`<span>${t('guest')} ${i}${i===1?' *':''}</span><input name="guest_${i}" maxlength="80" required>`;guestNames.appendChild(l)}}persons.onchange=renderGuests;renderGuests();
function attending(){return form.elements.attending.value==='yes'}form.querySelectorAll('[name=attending]').forEach(r=>r.onchange=()=>{$('#attendingFields').classList.toggle('hidden',!attending())});
function deadlinePassed(){return Date.now()>new Date(cfg.rsvpDeadline).getTime()}if(deadlinePassed()){form.innerHTML=`<p class="status">${t('closed')}</p>`}
form?.addEventListener('submit',async e=>{e.preventDefault();if(deadlinePassed()){status.textContent=t('closed');return}const fd=new FormData(form);const isGoing=fd.get('attending')==='yes';const payload={action:'rsvp',attending:isGoing,name:(fd.get('name')||'').trim(),phone:(fd.get('phone')||'').trim(),persons:isGoing?Number(fd.get('persons')):0,guestNames:isGoing?Array.from({length:Number(fd.get('persons'))},(_,i)=>(fd.get(`guest_${i+1}`)||'').trim()):[],note:(fd.get('note')||'').trim(),locale:lang};if(!payload.name||!payload.phone||(isGoing&&payload.guestNames.some(n=>!n))){status.textContent=lang==='ar'?'من فضلك أكمل كل البيانات المطلوبة.':'Please complete all required fields.';return}if(!cfg.appsScriptUrl){status.textContent=t('configure');return}status.textContent='…';try{const res=await fetch(cfg.appsScriptUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});const data=await res.json();if(!data.ok){status.textContent=data.error==='RSVP_CLOSED'?t('closed'):(lang==='ar'?'حصلت مشكلة أثناء إرسال التأكيد. حاول مرة تانية.':'Could not submit. Please try again.');return}status.textContent=data.status==='Waiting List'?t('waiting'):isGoing?t('success'):t('declined')}catch(err){status.textContent='Could not submit. Please try again.'}});
const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>obs.observe(x));translate();
