const CAPACITY=70;
const RSVP_SHEET='RSVPs';
const SUMMARY_SHEET='Summary';
const SPREADSHEET_ID='1R51EouqIvAo6VPlk13Xqo06CRqCq6WNrJ-KmMId-Bd8';
const NOTIFY_EMAIL='zeka.bolbol@gmail.com';
const DEADLINE=new Date('2026-10-01T23:59:59+03:00');
function doPost(e){try{if(new Date()>DEADLINE)return json({ok:false,error:'RSVP_CLOSED'});const p=JSON.parse(e.postData.contents||'{}');if(p.action!=='rsvp')return json({ok:false,error:'BAD_ACTION'});const lock=LockService.getScriptLock();lock.waitLock(15000);try{setup_();const result=upsert_(p);promoteWaitingList_();notify_(p,result);return json({ok:true,status:result.status});}finally{lock.releaseLock()}}catch(err){return json({ok:false,error:String(err.message||err)})}}
function spreadsheet_(){return SpreadsheetApp.openById(SPREADSHEET_ID)}
function setup_(){const ss=spreadsheet_();let s=ss.getSheetByName(RSVP_SHEET);if(!s){s=ss.insertSheet(RSVP_SHEET);s.appendRow(['Timestamp','Main Guest','Phone','Attending','Persons','Guest 1','Guest 2','Guest 3','Guest 4','Status','Happy Note','Updated At']);s.setFrozenRows(1)}let sum=ss.getSheetByName(SUMMARY_SHEET);if(!sum){sum=ss.insertSheet(SUMMARY_SHEET);sum.setFrozenRows(1)}sum.getRange('A4:B10').setValues([['Metric','Value'],['Capacity',CAPACITY],['Confirmed Persons',`=SUMIF(${RSVP_SHEET}!J:J,"Confirmed",${RSVP_SHEET}!E:E)`],['Remaining Seats','=MAX(0,B5-B6)'],['Waiting List Persons',`=SUMIF(${RSVP_SHEET}!J:J,"Waiting List",${RSVP_SHEET}!E:E)`],['Declined Responses',`=COUNTIF(${RSVP_SHEET}!J:J,"Declined")`],['Total RSVP Responses',`=COUNTA(${RSVP_SHEET}!B:B)-1`]]);}
function normalizePhone_(v){return String(v||'').replace(/[^0-9+]/g,'').replace(/^0020/,'+20').replace(/^01/,'+201')}
function confirmedPersons_(excludeRow){const s=spreadsheet_().getSheetByName(RSVP_SHEET);if(s.getLastRow()<2)return 0;const vals=s.getRange(2,1,s.getLastRow()-1,12).getValues();return vals.reduce((n,r,i)=>n+((i+2)!==excludeRow&&r[9]==='Confirmed'?Number(r[4]||0):0),0)}
function findByPhone_(phone){const s=spreadsheet_().getSheetByName(RSVP_SHEET);if(s.getLastRow()<2)return 0;const phones=s.getRange(2,3,s.getLastRow()-1,1).getValues().flat();const target=normalizePhone_(phone);const idx=phones.findIndex(x=>normalizePhone_(x)===target);return idx<0?0:idx+2}
function upsert_(p){const s=spreadsheet_().getSheetByName(RSVP_SHEET);const phone=normalizePhone_(p.phone);let row=findByPhone_(phone);if(!p.attending){const values=[new Date(),p.name||'',phone,'No',0,'','','','', 'Declined',p.note||'',new Date()];if(row)s.getRange(row,1,1,12).setValues([values]);else{s.appendRow(values);row=s.getLastRow()}return {row,status:'Declined'}}const count=Math.max(1,Math.min(4,Number(p.persons)||1));const names=(p.guestNames||[]).slice(0,4);while(names.length<4)names.push('');const available=CAPACITY-confirmedPersons_(row||0);const status=count<=available?'Confirmed':'Waiting List';const created=row?s.getRange(row,1).getValue():new Date();const values=[created||new Date(),p.name||names[0]||'',phone,'Yes',count,names[0],names[1],names[2],names[3],status,p.note||'',new Date()];if(row)s.getRange(row,1,1,12).setValues([values]);else{s.appendRow(values);row=s.getLastRow()}return {row,status}}
function promoteWaitingList_(){const s=spreadsheet_().getSheetByName(RSVP_SHEET);if(s.getLastRow()<2)return;const rows=s.getRange(2,1,s.getLastRow()-1,12).getValues();let used=rows.reduce((n,r)=>n+(r[9]==='Confirmed'?Number(r[4]||0):0),0);rows.map((r,i)=>({r,row:i+2})).filter(x=>x.r[9]==='Waiting List').sort((a,b)=>new Date(a.r[0])-new Date(b.r[0])).forEach(x=>{const n=Number(x.r[4]||0);if(used+n<=CAPACITY){s.getRange(x.row,10).setValue('Confirmed');s.getRange(x.row,12).setValue(new Date());used+=n;MailApp.sendEmail(NOTIFY_EMAIL,'Waiting list promotion — '+x.r[1],`${x.r[1]} (${x.r[2]}) was automatically promoted to Confirmed for ${n} person(s).`)}})}
function notify_(p,result){MailApp.sendEmail(NOTIFY_EMAIL,`Wedding RSVP — ${result.status} — ${p.name||'Guest'}`,`Status: ${result.status}\nName: ${p.name||''}\nPhone: ${p.phone||''}\nPersons: ${p.persons||0}\nGuests: ${(p.guestNames||[]).join(', ')}\nNote: ${p.note||''}`)}
function json(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
